const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
let data={};const context={window:{},crypto,navigator:{locks:{request:async(k,fn)=>fn()}},localStorage:{getItem:k=>data[k]||null,setItem:(k,v)=>{data[k]=v}}};vm.createContext(context);vm.runInContext(fs.readFileSync('static/local-data.js','utf8'),context);const local=context.window.MezunLocal,request=local.request;
(async()=>{const p=await request('/profile',{method:'POST',body:JSON.stringify({program:'CS',term:'202501'})});const root='/profile/'+p.id;
const c={code:'CS 210',name:'Algorithms',ects:6,su:3,status:'completed',categories:['Alan']};await request(root+'/courses',{method:'PUT',body:JSON.stringify(c)});assert.equal((await request(root+'/courses'))[0].code,'DSA 210');
await assert.rejects(request(root+'/courses/bulk',{method:'POST',body:JSON.stringify({courses:[{...c,code:'MATH 101'},c]})}));assert.equal((await request(root+'/courses')).length,1);
const before=(await request(root+'/courses'))[0],after={...before,status:'planned',planned_term:'203901'};await request(root+'/courses',{method:'PUT',body:JSON.stringify(after)});await request(root+'/courses/undo',{method:'POST',body:JSON.stringify({before,after})});assert.equal((await request(root+'/courses'))[0].status,'completed');await assert.rejects(request(root+'/courses/undo',{method:'POST',body:JSON.stringify({before,after})}));
const backup=await request(root+'/backup'),restored=await request('/restore',{method:'POST',body:JSON.stringify(backup)});assert.notEqual(restored.id,p.id);assert.equal((await request('/profile/'+restored.id+'/courses')).length,1);
const ev=await local.evaluate(p,[before,{...before,code:'MATH 101',status:'planned'}],{required:{ects:240},courses:[],requirements:[{name:'Alan',min_ects:12,min_su:null,min_count:null}]},async()=>({basic:null,engineering:2}));assert.equal(ev.completed.ects,6);assert.equal(ev.planned.ects,6);assert.equal(ev.projected.ects,12);assert.equal(ev.requirements[0].threshold_met_provisionally,false);assert.equal(ev.requirements[0].projected_threshold_met_provisionally,true);
context.localStorage.setItem=()=>{throw Error('quota')};await assert.rejects(request(root+'/courses',{method:'PUT',body:JSON.stringify({...c,code:'MATH 101'})}),/Kayıt yapılamadı/);assert.equal((await request(root+'/courses')).length,1);data={};await assert.rejects(request(root));console.log('Local storage, aliases, atomic bulk, undo conflicts, restore, evaluation, quota and isolation passed.');})().catch(e=>{console.error(e);process.exit(1)});
